---

name: Build and push GO-HTTP-REPLICATOR image

env:
  ALPINE_VERSION: "3.10"
  IMAGE: keep2share/go-http-replicator
  TAG: latest

on:
  schedule:
    # At 05:00 on day-of-month 14.
    - cron: '0 5 14 * *'  
  push:
    branches:
      - master

jobs:

  build-go-http-replicator:
    name: Build and push GO-HTTP-REPLICATOR image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
      -
        name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deploy
          SLACK_USERNAME: GitHub Actions
          SLACK_ICON: https://avatars.githubusercontent.com/u/44036562?s=200&v=4
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: Commit message
          SLACK_FOOTER: ''
